"""fix: users

Revision ID: 85967aecdd6b
Revises: a00867df4060
Create Date: 2025-03-05 17:13:01.728340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85967aecdd6b"
down_revision: Union[str, None] = "a00867df4060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "referal_code", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "referal_code", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
